services:
    app:
        build:
            context: .
        env_file: .env
        ports:
            - "8000:80"
        container_name: bravoure-app
        volumes:
            - .:/var/www/html:rw
            - storage_data:/var/www/html/storage
            - bootstrap_cache_data:/var/www/html/bootstrap/cache
        depends_on:
            - db

    db:
        platform: "linux/amd64"
        image: mysql:5.7
        container_name: bravoure-db
        env_file: .env
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: bravoure_db

        volumes:
            - dbdata:/var/lib/mysql
        ports:
            - "3306:3306"

volumes:
    dbdata:
    storage_data:
    bootstrap_cache_data:
